package com.example.ooad.jpa;

import com.example.ooad.jpa.entity.AdminUser;
import org.springframework.data.repository.CrudRepository;

/**
 * This interface is used to expose CRUD (Create, Read, Update, Delete) functions over the Entity created under entity
 * package. Additional methods can be defined just by adding method signature here. For ex: findByUserName.
 * Note that we do not need to implement this interface as actual implementation classes would be auto-generated by
 * JPA library.
 */
public interface AdminUserRepository extends CrudRepository<AdminUser, Long> {
    AdminUser findByUserName(String userName);
}
